#*************EN*************
# Use the ยง symbol for color coding
# Color code list https://minecraft.tools/en/color-code.php
# Use {name} for the name of the player who execute the command

#*************FR*************
# Utilisez le simbole ยง pour mettre de la couleur
# Liste des codes couleur https://minecraft.tools/fr/color-code.php
# Utilisez {name} pour le nom du joueur qui execute la commande

message: "messageheuh"
time: "5" time in seconds